"""RACS v0.2 canonical contract bindings.

Stage 3A — canonicalization kernel (RFC 8785 + sha256 digests).
Stage 3B — typed model bindings for the v0.2 payload schemas.
Stage 3C — runtime conformance: schema validation and cross-artifact verification.
Runtime continuity — active execution, observation, intervention and recovery payloads.
"""
from .canonical import canonical_bytes, canonical_str
from .digest import sha256_digest, verify_payload_digest
from .models import (
    AdmissibilityDetermination,
    AdmissibilityState,
    ConsequenceClass,
    Decision,
    EvaluationBinding,
    GovernanceClearance,
    GovernanceEvaluation,
    Reversibility,
    Status,
)
from .continuity import (
    CompletionContract,
    ContinuityDecision,
    ContinuityDecisionType,
    EnvironmentGovernanceProfile,
    ExecutorBinding,
    ExecutorType,
    FailClosedPolicy,
    GovernedCapabilityManifest,
    GovernedExecutionSession,
    HumanPresenceMode,
    InterventionReceipt,
    InterventionResult,
    InterventionType,
    ObservationQuality,
    ObservationSourceType,
    ProgressContract,
    RecoveryBudget,
    RecoveryNextState,
    RecoveryPlan,
    RecoveryReceipt,
    RecoveryResult,
    RuntimeObservation,
    SessionState,
    SignalClass,
)
from .validation import (
    ARTIFACT_TYPES,
    REASON_ACCEPT,
    Raw,
    Validated,
    ValidationResult,
    Verified,
    check,
    schema_sha256,
    validate,
)
from .continuity_validation import CONTINUITY_ARTIFACT_TYPES
from .verification import (
    VerificationResult,
    verify_clearance_binding,
    verify_evaluation_binding,
)

__all__ = [
    "canonical_bytes",
    "canonical_str",
    "sha256_digest",
    "verify_payload_digest",
    "GovernanceEvaluation",
    "AdmissibilityDetermination",
    "GovernanceClearance",
    "EvaluationBinding",
    "Decision",
    "Status",
    "AdmissibilityState",
    "ConsequenceClass",
    "Reversibility",
    "GovernedCapabilityManifest",
    "EnvironmentGovernanceProfile",
    "GovernedExecutionSession",
    "RuntimeObservation",
    "ContinuityDecision",
    "InterventionReceipt",
    "RecoveryPlan",
    "RecoveryReceipt",
    "ProgressContract",
    "CompletionContract",
    "ExecutorBinding",
    "RecoveryBudget",
    "ExecutorType",
    "HumanPresenceMode",
    "FailClosedPolicy",
    "SessionState",
    "ObservationSourceType",
    "SignalClass",
    "ObservationQuality",
    "ContinuityDecisionType",
    "InterventionType",
    "InterventionResult",
    "RecoveryResult",
    "RecoveryNextState",
    "ARTIFACT_TYPES",
    "CONTINUITY_ARTIFACT_TYPES",
    "REASON_ACCEPT",
    "Raw",
    "Validated",
    "Verified",
    "ValidationResult",
    "check",
    "validate",
    "schema_sha256",
    "VerificationResult",
    "verify_clearance_binding",
    "verify_evaluation_binding",
]
